apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-eks-cluster
  annotations:
    github.com/project-slug: prayankag/aws-eks-demo
  description: AWS EKS cluster managed by Terraform
  tags:
    - aws
    - eks
    - terraform
spec:
  type: service
  lifecycle: experimental
  owner: prayankag
